### ISSUE TITLE
Encountered duration limitation

### ISSUE THREAD

**Issue by Dev-seD** [x42/sound-gambit#5]
Hi,
A few words about your sound-gambit v0.6 application.
Its use is simple and the result is there.
However, I encountered a limitation on the maximum duration that the audio source file can have.
Above this duration, there is silence...
-Src Wav 24b 48k stereo Max 04:08:33.000
-Src Wav 16b 48k stereo Max 06:12:49.000
Do you think this could be improved?
Are you aware of any possible workaround?
Best regards,

**Comment by x42** [comment]
This is a limitation of the WAV file format. There is a 32bit index, and many applications (incorrectly) use a signed integer, so to be safe libsndfile allows for at most 2^31 frames:

2^31 [frames] / 48000 [frames/sec] / 2 [bytes/frame] /  60 [sec/min] = 372.82 min = 6h 12min 49.2 sec

The solution is to use `.w64` (64bit wave) instead of `.wav` -- or some other file format that does not have this limit.

see http://libsndfile.github.io/libsndfile/formats.html for supported file-formats and codecs.

**Comment by Dev-seD** [comment]
Hi Robin,
Thank you for your quick help and advice.
It's true, in .w64 format it works well with long durations.
I'm considering limiting the use of .w64 to longer durations and keeping 'wav(w32)' for shorter durations
Or
Using .w64 in all cases.
After listening, I don't feel like the switch to .w64 noticeably alters the signal.
What do you think?
Best regards

**Comment by Dev-seD** [comment]
It's perfect and lossless 
Thank you
